import 'package:flutter/foundation.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/services/remote_data_cache.dart';
import '../models/day_detail_model.dart';

class DayDetailLocalDatasource {
  final RemoteDataCache _cache;

  DayDetailLocalDatasource(this._cache);

  /// Loads the per-day detail JSON from B2/cache and parses it into [DayDetailModel].
  ///
  /// File path: `data/day_details/YYYY-MM-DD.json`
  /// Generated by `scripts/excel_to_json.py` — contains the full nested structure
  /// that [DayDetailModel.fromJson] expects, with all data intact:
  ///   gregorian, tibetan, significance (day_significance, element_combo + meaning),
  ///   auspicious_day (with short descriptions), astrology_cards (with status_bo,
  ///   image_key, popup_ref), torma_offering, empty_vase, daily_restriction,
  ///   auspicious_times, events.
  Future<DayDetailModel?> getDayDetail(String dateKey) async {
    try {
      final json = await _cache.getJson(AppConstants.dayDetailPath(dateKey));
      return DayDetailModel.fromJson(json);
    } catch (e, st) {
      debugPrint('getDayDetail: $dateKey failed — $e\n$st');
      return null;
    }
  }
}
